### ISSUE TITLE
'react-square-web-payments-sdk' does not contain a default export (imported as 'SquarePaymentsForm')

### ISSUE THREAD

**Issue by v1ra1** [weareseeed/react-square-web-payments-sdk#27]
### What version of React are you using?

17.02

### What version of Node.js are you using?

16.13.0

### What browser are you using?

97

### What operating system are you using?

Windows 10

### How are you deploying your application?

yarn start

### Describe the Bug

`import SquarePaymentsForm, { CreditCardInput } from 'react-square-web-payments-sdk';`

Using:

`<SquarePaymentsForm
              /**
               * Identifies the calling form with a verified application ID
               * generated from the Square Application Dashboard.
               */
              applicationId="sq0idp-Y0QZQ-Xx-Xx-Xx-Xx"
              /**
               * Invoked when payment form receives the result of a tokenize generation request.
               * The result will be a valid credit card or wallet token, or an error.
               */
              cardTokenizeResponseReceived={(token, buyer) => {
                console.info({ token, buyer });
              }}
              /**
               * This function enable the Strong Customer Authentication (SCA) flow
               *
               * We strongly recommend use this function to verify the buyer and
               * reduce the chance of fraudulent transactions.
               */
              createVerificationDetails={() => ({
                amount: '1.00',
                /* collected from the buyer */
                billingContact: {
                  addressLines: ['123 Main Street', 'Apartment 1'],
                  familyName: 'Doe',
                  givenName: 'John',
                  countryCode: 'GB',
                  city: 'London',
                },
                currencyCode: 'GBP',
                intent: 'CHARGE',
              })}
              /**
               * Identifies the location of the merchant that is taking the payment.
               * Obtained from the Square Application Dashboard - Locations tab.
               */
              locationId="LID"
            >
              <CreditCardInput />
            </SquarePaymentsForm>`
            
In a component.

Result:

`Attempted import error: 'react-square-web-payments-sdk' does not contain a default export (imported as 'SquarePaymentsForm').`

### Expected Behavior

It to load the square form or have a default export?

### To Reproduce

Just load it in on a standard react project.

**Comment by v1ra1** [comment]
`import { CreditCardInput, SquarePaymentsForm } from 'react-square-web-payments-sdk';`

This is what fixed it.

**Comment by mallen13** [comment]
I tried the mentioned solution to resolve, with he copied and pasted code into my react project,  but still get an error. 

`Attempted import error: 'payments' is not exported from '@square/web-sdk' (imported as '$6CgYg$payments').`

**Comment by yousafnawaz** [comment]
> I tried the mentioned solution to resolve, with the copied and pasted code into my react project, but still get an error.
> 
> `Attempted import error: 'payments' is not exported from '@square/web-sdk' (imported as '$6CgYg$payments').`

I am facing the same issue, anyone knows how to resolve this?

**Comment by danestves** [comment]
We will be looking into this issue, but please create a new one with that error

cc @gabrielelpidio
