### ISSUE TITLE
Pay Button active while waiting for cardTokenizeResponseReceived

### ISSUE THREAD

**Issue by Ryanklingert** [weareseeed/react-square-web-payments-sdk#3]
### Describe the feature you'd like to request

Right now the credit card pay button remains active while waiting for the cardTokenizeResponseReceived to be called and there is no indication that the button has been pressed / anything is happing. 

### Describe the solution you'd like

It would be great if the button was disabled and some sort of loading indication was displayed in order to inform the user that they don't need to press the button multiple times. 

### Describe alternatives you've considered

N/A

**Comment by danestves** [comment]
Thank you for this issue! We will be working on this and keep it you updated

**Comment by danestves** [comment]
Hi @Ryanklingert just to tell you that this feature will be released on `v2.0.0`!
