### ISSUE TITLE
Add ability to override 'loading' state of submit button in `CreditCardInput`

### ISSUE THREAD

**Issue by man-of-seafood** [weareseeed/react-square-web-payments-sdk#48]
### Describe the feature you'd like to request

For this particular use case at @square, we're using the wrapper to capture card data, which is (1) tokenized, and then (2) that token is submitted to another backend service to actually create the card. 
This wrapper automatically handles the loading/disabled state associated with (1). The issue is that the 'save' button on the credit card input is only hooked up to (1), meaning as soon as the token is received, the button goes from the grayed-out/disabled state to enabled again, but we then immediately kick off another action we need to wait on, and the button remains enabled while that action is processing in the backend. We'd also prefer not to completely hide the button to display a separate loading indicator, since this 2 step process should be abstracted away for the user. 

With that said, we'd like the ability to override the `loading` state of the submit button, which would then affect the disabled state of the button as well.

### Describe the solution you'd like

Expose a prop on the `CreditCardInput` named something like `isLoading` or `isProcessing` that, when true, will disable the button.

### Describe alternatives you've considered

I've considered supplying the `submitButtonId` to `CreditCardInput` and then doing
```
const submitButton = document.getElementById(submitButtonId)` 
submitButton.disabled = true;
```
This works well in the success case since we replace the view of the credit card input with a success modal (meaning the fact we never re-enable the button is not noticed). However, in the case an error comes back from the server, the button then also needs to be imperatively re-enabled.

Additionally, I do see that if you supply a function to children ([code](https://github.com/weareseeed/react-square-web-payments-sdk/blob/main/src/methods/CreditCardInput/index.tsx#L302)), you can replace the button wholesale to achieve whatever you want, but then I'd have to copy the styles out of the library to essentially duplicate the button to tweak the loading state handling. That syntax also ends out looking a bit awkward:
```
<CreditCardInput>
	children={MyDuplicatedButtonComponent.bind(null, props)}
</CreditCardInput>
```

**Comment by danestves** [comment]
For this particular issue, we are using internally `!card || isSubmitting` but we can offer something like `props.isLoading || (!card || isSubmitting)` what do you think about it?

Also in the `v3.0.0` we are making the render prop more usable for the user 😊

**Comment by man-of-seafood** [comment]
I think that logic looks good!

And that is great to hear - looking forward to trying out the next major version 😄 

And re: integrating this enhancement, AFAIU this change would entail a minor version bump - roughly what would the timeline look for that? No pressure, just curious for my own planning purposes.

Thanks for your work on this, btw!

**Comment by danestves** [comment]
We are planning to release the v3 this week, will have some breaking changes, so we are now writing the docs (we get rid of Storybook and write our docs using Next.js + MDX)

Also, if you want to play with the canary version we have the latest changes on `react-square-web-payments-sdk@canary` including types for Afterpay/Clearpay and callbacks for Gift Card and Credit Card

**Comment by man-of-seafood** [comment]
Will give it a try, thanks for the quick turnaround!

**Comment by danestves** [comment]
Hey @man-of-seafood we have published another version of canary and we introduce `isLoading` for ACH and Gift Card too

**Comment by danestves** [comment]
New version is published https://github.com/weareseeed/react-square-web-payments-sdk/releases/tag/v3.0.0
