### ISSUE TITLE
Add ability to surface custom error text

### ISSUE THREAD

**Issue by man-of-seafood** [weareseeed/react-square-web-payments-sdk#49]
### Describe the feature you'd like to request

**Context:** Similar my previous issue ([link](https://github.com/weareseeed/react-square-web-payments-sdk/issues/48)) - capturing card details and creating the card on the backend is a 2 step process, the 2nd of which could yield an error from the backend. In those cases, we'd like to be able to display the error from the backend.

### Describe the solution you'd like

Expose a prop on the `CreditCardInput` named something like `errorText` that, when present, will render in the same place and with the same styles as the frontend validation error text. It would also trigger the error styling (red border, iirc). Assuming both a frontend validation error and an error supplied via `errorText` are present, I think the most flexible thing to do would be to render the `errorText` below the frontend validation error text. Likely having both of these present at the same time indicates a logical error, but imo that will at least be quickly apparent to the dev when they see both at the same time. And in the case both are actually needed, it's possible to display both. 

### Describe alternatives you've considered

Placing the error text elsewhere (i.e. somewhere in the component tree that we control). However, it seems most natural to surface the backend validation error in the same place.

**Comment by danestves** [comment]
Hi @man-of-seafood! After reading some of the docs I have seen this prop on the Square SDK `setError` https://developer.squareup.com/reference/sdks/web/payments/card-payments#Card.setError so, I think we can add it as a prop for the Credit Card input, and also watch any other method that make use of this prop

**Comment by danestves** [comment]
Oh yeah, that is true! I'm thinking that we can introduce a `setError` function that receive an error string and style it like Square shows the errors, if no string is passed we use a generic error when calling that function like `There was an error creating the payment, please try again`

**Comment by danestves** [comment]
![Custom error message](https://user-images.githubusercontent.com/31737273/165601638-68fb2a29-f0b0-4619-a459-8aef07dfb57e.png)

I have been playing around about this, what do you think?

**Comment by man-of-seafood** [comment]
After speaking with our team more about it, we'll be going with a different error-surfacing strategy, but I appreciate the proposed solution. And I'll see if I can find who works on the SDK to see if they'd consider exposing a hook to set error text in the standard spot which might make things easier!

**Comment by danestves** [comment]
Perfect! So, we can close this issue for now and reopen it if there is any update from Square?

**Comment by man-of-seafood** [comment]
Yes - closing it out!
