### ISSUE TITLE
Add `onClick` handler to pay/save button

### ISSUE THREAD

**Issue by man-of-seafood** [weareseeed/react-square-web-payments-sdk#50]
### Describe the feature you'd like to request

Context: Trying to add an `onClick` listener to the save button, but there isn't a way to do that. 
I see there's the `submit` prop (added [here](https://github.com/weareseeed/react-square-web-payments-sdk/blob/main/src/methods/CreditCardInput/index.tsx#L272)), which I thought would be triggered on submission (i.e. on click), but the official SDK [docs](https://developer.squareup.com/reference/sdks/web/payments/enums/CardInputEventTypes#CardInputEventTypes.submit) say this event is only emitted `by pressing "Enter" while editing a field` (crucially, not on click). I have verified this by adding a log into my `submit` handler:
```
<CreditCardInput
  text="Text"
  submitButtonId={submitButtonId}
  children={isCardProcessing ? <LoadingIcon/> : null}
  submit={(e) => {
    console.log('executing submit callback') // never logged on click. does log on `enter`
    setIsCardProcessing(true)
  }}
/>
```

### Describe the solution you'd like

Add an `onClick` field to the `buttonProps` prop of the `CreditCardInput` (a la what you proposed [here](https://github.com/weareseeed/react-square-web-payments-sdk/issues/48#issuecomment-1111362255)). From there, pass it to the button.

### Describe alternatives you've considered

Passing the callback to the `submit` prop, but that's only triggered when you hit `Enter`.

**Comment by danestves** [comment]
<img width="429" alt="button props event listeners" src="https://user-images.githubusercontent.com/31737273/165649811-7399d9f5-9ac9-4455-81bb-1809bb69cfc7.png">

Hi @man-of-seafood currently in the `canary` version we support all kind of props for the button element, so you can write it and will appear all the methods that support it. Can you give it a try on `canary` and see if it's working?

**Comment by danestves** [comment]
We consider the `canary` version right now as "stable" now we are writing all the new docs

**Comment by danestves** [comment]
New version is published https://github.com/weareseeed/react-square-web-payments-sdk/releases/tag/v3.0.0
