### ISSUE TITLE
Error: Invalid Hook Call

### ISSUE THREAD

**Issue by singhdilip1007** [weareseeed/react-square-web-payments-sdk#51]
### What version of React are you using?

16.13.1

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

git deploymnet

### Describe the Bug

Hi All,
I've created my component with below details:
```JavaScript
import React from "react";
import {
    SquarePaymentsForm,
    CreditCardInput
} from "react-square-web-payments-sdk";

const PaymentFormSdk = () => {
    return (
        <SquarePaymentsForm applicationId="sandbox-************" locationId="*************">
            <CreditCardInput/>
        </SquarePaymentsForm>
    );
};
```
and calling this component on button click like below:
```HTML
 {
this.state.Isshowpayment == true ?
<div><PaymentFormSdk/></div>
 : null
}
```

once click on the button it's showing the error **Invalid hook call**. Please guide me, it is very urgent for me. 

Any help regarding the same will be highly appreciable. Thanks in advance.the 

### Expected Behavior

Should show credit card payment UI

### To Reproduce

N/A.
Just followed this link to integrate the same: https://www.npmjs.com/package/react-square-web-payments-sdk

**Comment by singhdilip1007** [comment]
@danestves  Here's the same:

https://codesandbox.io/embed/laughing-hooks-itsehd?fontsize=14&hidenavigation=1&theme=dark
<iframe src="https://codesandbox.io/embed/laughing-hooks-itsehd?fontsize=14&hidenavigation=1&theme=dark"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="laughing-hooks-itsehd"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
   
   in my case, I've a class component containing a button name as **Continue**.  On this button click have to open `Paymentform` component

**Comment by singhdilip1007** [comment]
@danestves Here's the same:
https://codesandbox.io/embed/festive-panka-einjbj?fontsize=14&hidenavigation=1&theme=dark

**Comment by danestves** [comment]
You can't have a class component with React Hooks, we don't support class components with our library, only hooks.

**Comment by singhdilip1007** [comment]
@danestves We've called square payment sdk inside only functional component. Look below:
```Javascript
<SquarePaymentsForm applicationId="sandbox-************" locationId="*************">
            <CreditCardInput/>
        </SquarePaymentsForm>
```

then calling this component inside a class component and in this case it must called I suppose. My whole application is based on class component & now I've to integrate square web payment SDK so please guide me on it.

Thanks in advance
