### ISSUE TITLE
Child prop for submit card payment button

### ISSUE THREAD

**Issue by WinglessFrame** [weareseeed/react-square-web-payments-sdk#8]
Would be cool to have control for children prop for submit button (for example, to put loader inside of the button and show it while processing payment on the backend)

To make this possible
```JSX
<CreditCardInput>
      <Loader loading={loading} />
</CreditCardInput>
```

**Comment by danestves** [comment]
Thanks, @WinglessFrame the version was updated and merged, this is the release notes https://github.com/weareseeed/react-square-web-payments-sdk/releases/tag/v1.5.2
